/** Auto-synced from Laravel ApiErrorCatalog — run prosperofy:export-error-catalog */

export const ERROR_MESSAGES: Record<string, string> = {
  "AUTH_UNAUTHENTICATED": "Your session expired. Please log in again.",
  "AUTH_FORBIDDEN": "You do not have permission to perform this action.",
  "POLICY_DENIED": "Forbidden.",
  "VALIDATION_ERROR": "Validation failed.",
  "HTTP_SESSION_EXPIRED": "Your session expired. Please refresh and try again.",
  "MODEL_NOT_FOUND": "The requested item could not be found.",
  "HTTP_NOT_FOUND": "The requested item could not be found.",
  "HTTP_METHOD_NOT_ALLOWED": "Method not allowed.",
  "HTTP_CONFLICT": "Conflict.",
  "HTTP_UNPROCESSABLE": "Unprocessable entity.",
  "HTTP_RATE_LIMIT": "Too many requests. Please wait a moment and try again.",
  "HTTP_CLIENT_ERROR": "We could not process your request. Please try again.",
  "SERVER_ERROR": "The server could not complete your request. Please try again shortly.",
  "STORAGE_UPLOAD_FAILED": "File upload failed. Please try again shortly.",
  "SIGNUP_CLOSED": "Registration is currently closed.",
  "WALLET_SERVICE_ERROR": "Wallet service is currently unavailable. Please try again shortly.",
  "WALLET_UNAVAILABLE": "Wallet service is temporarily unavailable. Please try again shortly.",
  "WALLET_RPC_TIMEOUT": "Blockchain network is temporarily unavailable. Please try again shortly.",
  "WALLET_VERIFY_FAILED": "Wallet signature verification failed. Please try again.",
  "WALLET_RATE_LIMIT": "Too many balance refreshes. Please try again in a moment.",
  "WALLET_REJECTED": "Wallet request could not be completed.",
  "WALLET_ALREADY_LINKED": "This wallet is already linked to another account.",
  "WALLET_NOT_FOUND": "No WFL Wallet found. Please activate your wallet first.",
  "WALLET_NOT_ACTIVE": "Your WFL Wallet is not active yet. Please try again shortly.",
  "WALLET_UPSTREAM_UNAVAILABLE": "Solana network data is temporarily unavailable. Please try again shortly.",
  "WALLET_SYNC_FAILED": "Wallet balance service is temporarily unavailable. Please try again shortly.",
  "WALLET_INVALID_ADDRESS": "The wallet address could not be validated.",
  "WALLET_ADDRESS_MISSING": "Solana receive address is not available for this wallet.",
  "WALLET_EVM_DISABLED": "Ethereum wallet routes are not enabled.",
  "NEWS_DATA_UNAVAILABLE": "News data is temporarily unavailable.",
  "WALLET_BUSINESS_ERROR": "Wallet request could not be completed.",
  "WALLET_CHAIN_NOT_SUPPORTED": "This network is not supported for sending yet.",
  "WALLET_CHALLENGE_NOT_FOUND": "This wallet connection request was not found. Please reconnect your wallet.",
  "WALLET_CHALLENGE_EXPIRED": "This wallet connection request expired. Please reconnect your wallet.",
  "WALLET_CHALLENGE_USED": "This wallet connection request was already used. Please start again.",
  "WALLET_CHALLENGE_INVALID": "This wallet connection expired. Please reconnect your wallet and try again.",
  "WALLET_CHALLENGE_MESSAGE_MISMATCH": "This wallet connection request could not be validated. Please reconnect your wallet.",
  "WALLET_PROVIDER_MISMATCH": "Wallet provider mismatch. Please reconnect your wallet.",
  "WALLET_CHAIN_MISMATCH": "Wallet provider mismatch. Please reconnect your wallet.",
  "WALLET_ADDRESS_MISMATCH": "Wallet address changed during connection. Please reconnect your wallet.",
  "WALLET_CHALLENGE_RACE": "This wallet connection request could not be completed. Please try again.",
  "WALLET_BALANCE_NOT_SYNCED": "Please refresh your wallet balance before sending.",
  "WALLET_BALANCE_STALE": "Please refresh your wallet balance before sending.",
  "WALLET_INSUFFICIENT_BALANCE_AFTER_FEE": "Insufficient SOL balance for this transaction after network fees.",
  "PREVIEW_CONSUMED": "This preview can no longer be used.",
  "PREVIEW_EXPIRED": "Transaction preview expired. Please create a new preview.",
  "WALLET_ERROR": "Unable to load wallet data right now. Please try again.",
  "SETTINGS_LOAD_FAILED": "Unable to load settings right now. Please try again.",
  "DASHBOARD_LOAD_FAILED": "Unable to load dashboard right now. Please try again.",
  "AGENTS_LOAD_FAILED": "Unable to load AI agents data right now. Please try again.",
  "AI_ERROR": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_UNAVAILABLE": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_NOT_CONFIGURED": "AI analysis is not available right now. Please try again later.",
  "AI_INVALID_JSON": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_CONNECTION": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_UNKNOWN": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_HTTP_ERROR": "AI analysis is temporarily unavailable. Please try again shortly.",
  "AI_BUSINESS_ERROR": "AI could not complete this request. Please adjust your inputs and try again.",
  "ORCH_INTERNAL": "AI analysis is temporarily unavailable. Please try again shortly.",
  "SIGNAL_PERSIST_FAILED": "The agent could not generate a signal right now. Please try again shortly.",
  "MARKET_UNAVAILABLE": "Market data is temporarily unavailable. Showing cached data if available.",
  "MARKET_WS_UNAVAILABLE": "Market data stream is temporarily unavailable.",
  "MARKET_PROVIDER_FAILED": "Market data is temporarily unavailable. Showing cached data if available.",
  "MARKET_GATEWAY_ERROR": "Market data is temporarily unavailable. Showing cached data if available.",
  "VERIFICATION_FAILED": "Verification failed. Please check your details and try again.",
  "INVALID_PASSWORD": "The current password is incorrect.",
  "INVALID_PASSPHRASE": "The passphrase is incorrect.",
  "EXCHANGE_VERIFY_FAILED": "Exchange credentials could not be verified.",
  "TEMPORARY_URL_NOT_ALLOWED": "Temporary URLs are not allowed for this file type.",
  "REWARD_CLAIM_DENIED": "This reward cannot be claimed right now.",
  "NOT_FOUND": "The requested item could not be found."
} as const;

export const ERROR_DATA_KEYS: Partial<Record<string, readonly string[]>> = {
  WALLET_BALANCE_STALE: ["balance_last_synced_at"],
  WALLET_INSUFFICIENT_BALANCE_AFTER_FEE: [
    "available_balance","requested_amount","estimated_fee_amount","safety_buffer_amount",
    "required_total","safe_required_total","max_sendable_amount",
  ],
  NEWS_DATA_UNAVAILABLE: ["articles","data_freshness","cached"],
};

export function getCatalogMessage(code: string): string | null {
  return ERROR_MESSAGES[code] ?? null;
}
