/** Auto-synced from Laravel ApiErrorCatalog — run prosperofy:export-error-catalog */

export const ERROR_MESSAGES: Record<string, string> = {
  "AGENT_ACCESS_DENIED": "You do not have access to this agent.",
  "AGENT_DAILY_TRADE_LIMIT_EXCEEDED": "Daily trade limit exceeded for this agent.",
  "AGENT_DISABLED": "Agents are not enabled on this platform.",
  "AGENT_EXCHANGE_CONNECTION_INVALID": "Exchange connection is invalid or unavailable.",
  "AGENT_EXCHANGE_CONNECTION_REQUIRED": "A valid exchange connection is required.",
  "AGENT_EXECUTABLE_TRADES_AGENT_TYPE_NOT_ALLOWED": "This agent type cannot prepare executable trades. Choose Trade suggestion, Portfolio monitor, or Custom.",
  "AGENT_EXECUTABLE_TRADES_DISABLED": "Executable trade preparation is disabled by platform settings.",
  "AGENT_EXECUTABLE_TRADES_REQUIRE_RISK_CONFIRMATION": "Accept the trading risk confirmations to continue.",
  "AGENT_EXECUTABLE_TRADES_REQUIRE_SUGGESTIONS": "Enable trade suggestions before preparing executable trades.",
  "AGENT_EXECUTABLE_TRADES_REQUIRE_VALID_EXCHANGE": "Connect a valid exchange before enabling executable trade preparation.",
  "AGENT_EXECUTABLE_TRADES_WITHDRAWAL_PERMISSION_NOT_ALLOWED": "Withdrawal permission must remain disabled on your exchange API key.",
  "AGENT_LOAD_FAILED": "Agents could not be loaded.",
  "AGENT_NOT_FOUND": "Agent not found.",
  "AGENT_RUN_FAILED": "Agent run could not be completed.",
  "AGENT_SYMBOL_REQUIRED": "Choose a symbol before creating a trade suggestion.",
  "AGENT_TRADE_EXECUTION_DISABLED": "Agent trade execution is not enabled.",
  "AGENT_TRADE_EXECUTION_NOT_ALLOWED": "This trade cannot be executed.",
  "AGENT_TRADE_RISK_CONFIRMATION_REQUIRED": "Risk confirmations are required before executing this trade.",
  "AGENT_TRADE_SUGGESTION_EXPIRED": "This trade suggestion has expired.",
  "AGENT_TRADE_SUGGESTION_FAILED": "Trade suggestion could not be created.",
  "AGENT_TRADE_SUGGESTIONS_DISABLED": "Trade suggestions are not enabled for this agent.",
  "AGENT_TRAINING_DATA_RECORD_FAILED": "Training data could not be recorded.",
  "AGENT_VALIDATION_FAILED": "Agent validation failed.",
  "AI_ACTION_FAILED": "We could not create this recommendation right now. Please try again.",
  "AI_ACTION_LIMIT_REACHED": "You have reached your monthly AI action limit. Upgrade your membership for more.",
  "AI_ACTION_UNKNOWN": "That action is not available right now.",
  "AI_RECOMMENDATION_ACCESS_DENIED": "You do not have access to this recommendation.",
  "AI_RECOMMENDATION_NOT_FOUND": "The requested recommendation could not be found.",
  "AI_VALIDATION_FAILED": "That action is not available right now.",
  "AUTH_FORBIDDEN": "You do not have permission to perform this action.",
  "AUTH_UNAUTHENTICATED": "Your session expired. Please log in again.",
  "BILLING_ALREADY_ON_PLAN": "You are already on this membership plan.",
  "BILLING_CHECKOUT_FAILED": "We could not start checkout. Please try again shortly.",
  "BILLING_PAYMENT_NOT_FOUND": "The requested billing payment could not be found.",
  "BILLING_PLAN_NOT_FOUND": "The requested subscription plan could not be found.",
  "BILLING_SUBSCRIPTION_NOT_FOUND": "No subscription was found for your account.",
  "BINANCE_API_INVALID": "Binance API key or secret is invalid.",
  "BINANCE_API_PERMISSION_DENIED": "Your API key may be restricted to another IP address. Add Prosperofy backend IP to Binance API restrictions or create a portfolio-only key.",
  "BINANCE_API_RATE_LIMITED": "Binance rate limit reached. Please try again shortly.",
  "BINANCE_API_TIMEOUT": "Binance did not respond in time. Please try again.",
  "BINANCE_API_TRADING_PERMISSION_REQUIRED": "Your API key only has Reading permission. Portfolio view is available, but trading is disabled.",
  "BINANCE_API_UNAVAILABLE": "Binance is temporarily unavailable. Please try again later.",
  "BINANCE_API_WITHDRAWAL_PERMISSION_NOT_ALLOWED": "Withdrawal permission is enabled. For safety, Prosperofy does not accept API keys with withdrawal permission.",
  "BINANCE_CONNECTION_ACCESS_DENIED": "You do not have access to this exchange connection.",
  "BINANCE_CONNECTION_DUPLICATE": "This API key is already connected to your account.",
  "BINANCE_CONNECTION_NOT_FOUND": "Exchange connection not found.",
  "BINANCE_ORDER_PLACE_FAILED": "Order could not be placed.",
  "BINANCE_ORDER_PREVIEW_FAILED": "Order preview could not be completed.",
  "BINANCE_PORTFOLIO_UNAVAILABLE": "Binance portfolio data is temporarily unavailable.",
  "BINANCE_TRADING_DISABLED": "Binance trading is not enabled on this platform.",
  "DASHBOARD_LOAD_FAILED": "Unable to load dashboard right now. Please try again.",
  "EXCHANGE_REVALIDATE_UNSUPPORTED": "Revalidation is only supported for Binance connections.",
  "EXCHANGE_SECRET_DECRYPTION_FAILED": "Could not read stored exchange credentials.",
  "EXCHANGE_SECRET_ENCRYPTION_FAILED": "Could not securely store exchange credentials.",
  "EXCHANGE_VERIFY_FAILED": "Exchange credentials could not be verified.",
  "HTTP_CLIENT_ERROR": "We could not process your request. Please try again.",
  "HTTP_CONFLICT": "Conflict.",
  "HTTP_METHOD_NOT_ALLOWED": "Method not allowed.",
  "HTTP_NOT_FOUND": "The requested item could not be found.",
  "HTTP_RATE_LIMIT": "Too many requests. Please wait a moment and try again.",
  "HTTP_SESSION_EXPIRED": "Your session expired. Please refresh and try again.",
  "HTTP_UNPROCESSABLE": "Unprocessable entity.",
  "INVALID_PASSPHRASE": "The passphrase is incorrect.",
  "INVALID_PASSWORD": "The current password is incorrect.",
  "MARKET_DATA_UNAVAILABLE": "Market data is temporarily unavailable. Please try again shortly.",
  "MARKET_GATEWAY_ERROR": "Market data is temporarily unavailable. Please try again shortly.",
  "MARKET_PROVIDER_FAILED": "Market data is temporarily unavailable. Please try again shortly.",
  "MARKET_PROVIDER_UNAVAILABLE": "Market data provider is temporarily unavailable. Please try again shortly.",
  "MARKET_SYMBOL_NOT_SUPPORTED": "This symbol is not supported on the configured market provider.",
  "MARKET_UNAVAILABLE": "Market data is temporarily unavailable. Please try again shortly.",
  "MARKET_WS_UNAVAILABLE": "Market data stream is temporarily unavailable.",
  "MODEL_NOT_FOUND": "The requested item could not be found.",
  "NEWS_DATA_UNAVAILABLE": "News data is temporarily unavailable.",
  "NOT_FOUND": "The requested item could not be found.",
  "ORCH_INTERNAL": "Service is temporarily unavailable. Please try again shortly.",
  "PAYMENT_ALREADY_PROCESSED": "This payment has already been processed.",
  "PAYMENT_CREATE_FAILED": "We could not create your payment. Please try again shortly.",
  "PAYMENT_IPN_INVALID": "Invalid payment notification.",
  "PAYMENT_IPN_SIGNATURE_INVALID": "Payment notification signature is invalid.",
  "PAYMENT_NOT_FOUND": "The requested payment could not be found.",
  "PAYMENT_PROVIDER_UNAVAILABLE": "Payment provider is not configured yet.",
  "POLICY_DENIED": "Forbidden.",
  "PREVIEW_CONSUMED": "This preview can no longer be used.",
  "PREVIEW_EXPIRED": "Transaction preview expired. Please create a new preview.",
  "SERVER_ERROR": "The server could not complete your request. Please try again shortly.",
  "SETTINGS_LOAD_FAILED": "Unable to load settings right now. Please try again.",
  "SIGNUP_CLOSED": "Registration is currently closed.",
  "STORAGE_UPLOAD_FAILED": "File upload failed. Please try again shortly.",
  "SUBSCRIPTION_ACTIVATION_FAILED": "Subscription activation failed. Please contact support.",
  "SUBSCRIPTION_LIMIT_EXCEEDED": "You have reached the limit for your current subscription plan.",
  "TEMPORARY_URL_NOT_ALLOWED": "Temporary URLs are not allowed for this file type.",
  "VALIDATION_ERROR": "Validation failed.",
  "VERIFICATION_FAILED": "Verification failed. Please check your details and try again.",
  "WALLET_ADDRESS_MISMATCH": "Wallet address changed during connection. Please reconnect your wallet.",
  "WALLET_ADDRESS_MISSING": "Solana receive address is not available for this wallet.",
  "WALLET_ALREADY_LINKED": "This wallet is already linked to another account.",
  "WALLET_BALANCE_NOT_SYNCED": "Please refresh your wallet balance before sending.",
  "WALLET_BALANCE_STALE": "Please refresh your wallet balance before sending.",
  "WALLET_BUSINESS_ERROR": "Wallet request could not be completed.",
  "WALLET_CHAIN_MISMATCH": "Wallet provider mismatch. Please reconnect your wallet.",
  "WALLET_CHAIN_NOT_SUPPORTED": "This network is not supported for sending yet.",
  "WALLET_CHALLENGE_EXPIRED": "This wallet connection request expired. Please reconnect your wallet.",
  "WALLET_CHALLENGE_INVALID": "This wallet connection expired. Please reconnect your wallet and try again.",
  "WALLET_CHALLENGE_MESSAGE_MISMATCH": "This wallet connection request could not be validated. Please reconnect your wallet.",
  "WALLET_CHALLENGE_NOT_FOUND": "This wallet connection request was not found. Please reconnect your wallet.",
  "WALLET_CHALLENGE_RACE": "This wallet connection request could not be completed. Please try again.",
  "WALLET_CHALLENGE_USED": "This wallet connection request was already used. Please start again.",
  "WALLET_ERROR": "Unable to load wallet data right now. Please try again.",
  "WALLET_EVM_DISABLED": "Ethereum wallet routes are not enabled.",
  "WALLET_INSUFFICIENT_BALANCE_AFTER_FEE": "Insufficient SOL balance for this transaction after network fees.",
  "WALLET_INVALID_ADDRESS": "The wallet address could not be validated.",
  "WALLET_NOT_ACTIVE": "Your WFL Wallet is not active yet. Please try again shortly.",
  "WALLET_NOT_FOUND": "No WFL Wallet found. Please activate your wallet first.",
  "WALLET_PROVIDER_MISMATCH": "Wallet provider mismatch. Please reconnect your wallet.",
  "WALLET_RATE_LIMIT": "Too many balance refreshes. Please try again in a moment.",
  "WALLET_REJECTED": "Wallet request could not be completed.",
  "WALLET_RPC_TIMEOUT": "Blockchain network is temporarily unavailable. Please try again shortly.",
  "WALLET_SERVICE_ERROR": "Wallet service is currently unavailable. Please try again shortly.",
  "WALLET_SYNC_FAILED": "Wallet balance service is temporarily unavailable. Please try again shortly.",
  "WALLET_UNAVAILABLE": "Wallet service is temporarily unavailable. Please try again shortly.",
  "WALLET_UPSTREAM_UNAVAILABLE": "Solana network data is temporarily unavailable. Please try again shortly.",
  "WALLET_VERIFY_FAILED": "Wallet signature verification failed. Please try again.",
} as const;

export const ERROR_DATA_KEYS: Partial<Record<string, readonly string[]>> = {
  WALLET_BALANCE_STALE: ["balance_last_synced_at"],
  WALLET_INSUFFICIENT_BALANCE_AFTER_FEE: [
    "available_balance","requested_amount","estimated_fee_amount","safety_buffer_amount",
    "required_total","safe_required_total","max_sendable_amount",
  ],
  NEWS_DATA_UNAVAILABLE: ["articles","data_freshness","cached"],
};

export function getCatalogMessage(code: string): string | null {
  return ERROR_MESSAGES[code] ?? null;
}