services:
  - name: web
    github:
      repo: https://github.com/Artixcore/prosperofy-app.git
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080

    envs:
      - key: NODE_ENV
        value: production

      - key: NEXT_PUBLIC_APP_URL
        value: https://app.prosperofy.com

      - key: NEXT_PUBLIC_LARAVEL_API_BASE_URL
        value: https://backend.prosperofy.com

      - key: APP_URL
        value: https://app.prosperofy.com

      - key: TRUSTED_HOSTS
        value: app.prosperofy.com